alias reload='source ~/.bashrc'

alias q='exit'

alias h='history'
alias hi='history | tail -20'

alias l='ls -laGFh'
alias ..='cd ..'
alias ...='cd ../..'
alias cdd='cd -'

alias numfiles='echo $(ls -1 | wc -l)'

alias psa='ps aux'
alias psg='ps aux | grep $1'

alias ka9='killall -9'
alias k9='kill -9'

alias df='df -h' # humanize sizes

alias pubkey='more ~/.ssh/id_rsa.pub'
alias hosts='more /etc/hosts'
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

alias tf='tail -f'
alias devlog='tail -f log/development.log'

alias post='curl -i -X POST'
alias get='curl -i -X GET'

alias gst='git status'
alias gco='git checkout'
alias gd='git diff'
alias gb='git branch'
alias gs='git show'
alias gcl='git clone'

alias rb='ruby'
alias rs='rails s'
alias rc='rails c'
alias rg='rails g'
alias rd='rails d'

alias gemi='gem install --no-ri --no-rdoc'
alias gemu='gem uninstall'

alias b='bundle'
alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'

alias rr='bundle exec rake routes'
alias rt='bundle exec rake -T --all'

alias notify="notify-send 'Listo' 'Aprieta!!!'"
alias fix_update='sudo rm /var/lib/pacman/db.lck'
